version: '3.8'

services:

  db:
    image: postgres:13-alpine
    volumes:
      - app-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=orange_users
      - POSTGRES_PASSWORD=orange_users
      - POSTGRES_DB=orange_users

  pgadmin:
    image: dpage/pgadmin4
    networks:
      - ${TRAEFIK_PUBLIC_NETWORK?Variable not set}
      - default
    depends_on:
      - db
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin

  backend:
    build: .
    depends_on:
      - db
    command:  uvicorn app.main:app --reload --workers 4 --host 0.0.0.0 --port 8000
    environment:
      - DB_URL=postgresql://orange_users:orange_users@db/orange_users

volumes:
    app-db-data:
